### ISSUE TITLE
DasMulli.Win32.ServiceUtils

### ISSUE THREAD

**Issue by hema2013** [dasMulli/dotnet-win32-service#74] opened 2018-05-15 14:02 UTC
Hello, 
 

- I have Create  a simple example (Console App .Net Core) :*

  public class ServiceHost : IWin32Service
    {
        public string ServiceName => "Test Service";

        public void Start(string[] startupArguments, ServiceStoppedCallback serviceStoppedCallback)
        {
            
        }

        public void Stop(){}
    }

static void Main(string[] args)
        {
            var host = new ServiceHost();
            var win32Host = new Win32ServiceHost(host);
            win32Host.Run();
        }

- I have install the service using the command "sc create" .
- The Service has been installed on the windows services.
- When I try to start it , Error Occurred
     "The Test Api Service service failed to start due to the following error: 
     The service did not respond to the start or control request in a timely fashion." 
- Why This Error Occurred although I do not write any code on the start method.
![capture](https://user-images.githubusercontent.com/5321239/40061491-b79d08e0-5861-11e8-87cd-f6c1cdfc1e73.PNG)

**Comment by dasMulli** [comment] 2018-05-16 18:10
what did you pass to `sc.exe`? what executable shown in the service details/properties in the service management console?

**Comment by mateusz-jablonski94** [comment] 2018-05-21 07:45
"Test Service" != "Test Api Service 22"

**Comment by dasMulli** [comment] 2018-05-22 05:31
@hema2013 also note that it may not work with the build output. try using `dotnet publish -r win-x64` and use the the executable in the `publish/` subdirectory of the output folder.
Using the build output may or may not work depending on service and system configurations (permissions).

**Comment by dasMulli** [comment] 2019-03-03 23:58
Closing due to the OP not responding, please comment if the issue is still not resolved!

**Closed by dasMulli** 2019-03-03 23:58 UTC
