### ISSUE TITLE
Getting error "The service process could not connect to the service controller"

### ISSUE THREAD

**Issue by manavjoshi08** [dasMulli/dotnet-win32-service#71] opened 2018-04-20 06:59 UTC
Hi Martin,

Am getting the following error while running directly in my console application. have attached an image.

Great library btw. Thanks
![error](https://user-images.githubusercontent.com/37800683/39035091-6c308fc8-4496-11e8-87a5-9ae794585513.png)

**Comment by dasMulli** [comment] 2018-04-20 07:46
When you run an app directly you can’t use the windows service functionality. It is only available when started from windows‘ service system. The demo application code in this repo checks for command line arguments that are added in the registration.

How does your startup code (Main function) look like?

**Comment by manavjoshi08** [comment] 2018-04-20 10:00
`namespace MyConsoleWindowsService
{
   public class Program
    {
        private static IConfiguration Configuration { get; set; }

        static void Main(string[] args)
        {
            var configBuilder = new ConfigurationBuilder()
                        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);

            Configuration = configBuilder.Build();

            var container = IocConfig();
            ICommand cmd = container.Resolve<Method1Command>();

            var myService = new RunAsService(cmd);
            var serviceHost = new Win32ServiceHost(myService);
            serviceHost.Run();

            Console.WriteLine("---------- PRESS ANY KEY TO EXIT ----------");
            Console.ReadKey();
        }
}
}`

**Comment by dasMulli** [comment] 2018-04-20 11:13
Yeah `serviceHost.Run()` will only work when started from the windows service subsystem as described above.

**Comment by dasMulli** [comment] 2018-04-27 11:25
Closing since behaviour is as designed.

**Closed by dasMulli** 2018-04-27 11:25 UTC
